name: pathole_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.2
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
